import App from "./App";
import RestrauntCard from "./RestrauntCard";
import Mobile from "./Mobile";

const mob_data=[
    {
       "id": 3804,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "3260546690071",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_MZSbdsq.png",
       "title": "Motorola G64 5G",
       "HSN": "85171300",
       "description": "",
       "mrp": 17999,
       "price": 14999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/158865-800-auto_pt5v4fC.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "motorola-g64-5g",
       "lastedit_date": "2024-04-23T12:36:34.370903",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 186,
       "sub_sub_category": null,
       "brand_name": 228,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "14999.0",
       "variant_id": "6967",
       "variant_name": "Motorola g64 5G (Mint Green, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/158870-800-auto_I4DRUK3.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3803,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "2894129484726",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_YubNoTd.png",
       "title": "OnePlus 12",
       "HSN": "85171300",
       "description": "\r\nDue to the mobile phone system file occupying space (including Android system and pre-installed apps), the available memory capacity is less than this value. Storage capacity will vary based on software version and may vary from device to device. 3. Photo pixels of different camera modes may vary, please refer to the actual situation. Video pixels of different shooting modes may also vary, please refer to the actual situation. 4. The battery of the OnePlus 12 adopts a serial dual-cell design, with a typical capacity of 2700mAh (7.82V), equivalent to 5400mAh (3.91V); typical energy: 21.12Wh. The rated capacity is 2630mAh (7.82V), equivalent to 5260mAh (3.91V); rated energy: 20.57Wh. The data is based on the OnePlus Test Laboratory calculation, and due to different individual usage habits, machine aging and other factors, the experience may vary, please refer to the actual experience. 5. Product pictures and content on the page are for illustrative purposes only. The actual results (including but not limited to appearance, color, size) and the screen display content (including but not limited to background, UI, and picture) may vary; 6. Numbers are theoretical, obtained under a controlled test environment (see each specific description) and provided by the supplier or the OnePlus laboratory. Actual performance may vary due to individual product differences, software versions, use conditions and environmental factors. Please refer to the actual experience. 7. Due to the real-time changes in product batches and supply factors, in order to provide accurate information on product information, specifications, and product characteristics, OnePlus may adjust and revise the text descriptions, picture effects, and other content on the above pages in real time to match the reality of the product performance, specifications, index, parts and other information; in the event that page modifications and adjustments are necessary, no special notice will be given. 8. The highest reported SAR value: Head SAR: 1.18W/kg; Body SAR: 0.68W/kg.",
       "mrp": 64999,
       "price": 62880,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Oneplus-12-5g-flowy-emerald-512gb-16gb-ram-Front-Back-View.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "oneplus-12",
       "lastedit_date": "2024-04-23T12:15:29.902455",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 188,
       "sub_sub_category": null,
       "brand_name": 226,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "62880.0",
       "variant_id": "6964",
       "variant_name": "OnePlus 12 (Silky Black, 256 GB) (12 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Oneplus-12-5g-silky-black-512gb-16gb-ram-Front-Back-View.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3802,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "6040275784508",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_7kPHFdl.png",
       "title": "OnePlus Nord CE4",
       "HSN": "85171300",
       "description": "The Qualcomm Snapdragon 7 Gen 3 chipset not only gives your Nord CE4 silly levels of OnePlus Fast and Smooth performance, but it also guards your battery life and maximizes power efficiency. What's more? You get to experience blazing download speeds up to 5Gbps deliver unceasing mobile gaming, work-from-anywhere productivity, and more OnePlus Nord CE4 comes in 2 colorways - Celadon Marble, a first for Nord and Dark Chrome, our signature variant. Oh, and it’s mega-durable… This phone’s bezel material is so tough, it’s thinking of taking up cage fighting. Seriously, we dropped it 1.5 meters onto marble, and it survived2. That’s tough as nails! Battery & Charging: The most powerful fast charging in Nord history, with 100W SuperVOOC charging and 5500mAh Battery. Handle your low battery woes like a boss with 100W SUPERVOOC fast charging that boosts your phone to 100% power in 30 minutes. Smart Charging 4.0 learns your usage habits to optimize charging and prevent overheating and battery aging. After 10mins charging (from 1%), you get to enjoy · 7.3hrs of video watching (app:YouTube) · 19.7hrs of music listening (app:Spotify) · 10.9hrs of voice calling (app: WhatsApp) · 6.7hrs of social media browsing (app:Instagram) · 3.9hrs of gaming (app:Battlegrounds India) No one likes a slow phone, so OnePlus Nord CE4 comes with 8GB of RAM and up to 8GB of virtual RAM expansion to keep your app switching and loading slick and speedy. Plus, you get lots of space for saving evidence of your adventures, with up to 256GB of storage (ROM) and a second SIM card slot that supports microSD cards for expandable storage up to 1TB! SONY LYT-600 (IMX882) 50MP camera sensor with OIS ensures that you get more stable and clearer pictures, no matter off road or uneven terrains, capture moving subjects and your unshakeable spirit. Further, with flagship-level RAW HDR algorithm, OnePlus Nord CE4 has better photography performance when taking portraits in sunny day.",
       "mrp": 24999,
       "price": 24389,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/1-M00-52-A5-CpgM7mYR-t-AD9lKAAWYyOWBY10861.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "oneplus-nord-ce4",
       "lastedit_date": "2024-04-23T12:12:43.858104",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 188,
       "sub_sub_category": null,
       "brand_name": 226,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "24389.0",
       "variant_id": "6960",
       "variant_name": "OnePlus Nord CE4 (Dark Chrome, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/1-M00-52-A2-CpgM7WYR-viATDPnAATPnD-sVqo964_LI0Dnzl.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3801,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "1551580772670",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_b4iEwVU.png",
       "title": "Motorola Edge 50 Pro 5G",
       "HSN": "85171300",
       "description": "Motorola Edge 50 Pro has an amalgamation of great designs and amazing features. It embodies a silicone vegan leather finish with a metal frame for a premium feel. Its 17.22 cm (6.7) curved display is Pantone validated for true colours. This 1.5K super HD display, supports HDR10+ and has a refresh rate of 144 Hz to give clear visual effects all the time. Capture beautiful photos with this 50 MP AI-powered camera with OIS that comes with Pantone-validated colours and a f/1.4 wide aperture making it good in low-light conditions. For shake-free videos, AI video stabilization comes in handy, while the AI phone enhancement engine improves image quality. There is also 13 MP ultrawide + macro camera, 10 MP telephoto camers with 30X hybrid zoom and OIS. Selfie camera is 50 MP Auto focus. With IP68 waterproofing, 125 W TurboPower charging, and Hello UI based on Android 14 it is a versatile powerful device. The Style Sync AI generative theming allows you to customize your experience.",
       "mrp": 36999,
       "price": 31999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/158838-800-auto_IU7J9bC.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "motorola-edge-50-pro-5g",
       "lastedit_date": "2024-04-23T12:55:17.229114",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 186,
       "sub_sub_category": null,
       "brand_name": 228,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "31999.0",
       "variant_id": "6954",
       "variant_name": "Motorola Edge 50 Pro 5G with 68W Charger (Luxe Lavender, 256 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/158845-800-auto_IZZDvbE.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3800,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "3582235086034",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_c1yd01v.png",
       "title": "Tecno Pova 6 Pro 5G",
       "HSN": "85171300",
       "description": "",
       "mrp": 22999,
       "price": 19999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Tecno-pova-6-pro-5g-comet-green-256gb-8gb-ram-Front-Back-View-Copy_CtAuHd5.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "tecno-pova-6-pro-5g",
       "lastedit_date": "2024-04-23T12:05:03.025029",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 179,
       "sub_sub_category": null,
       "brand_name": 224,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "19999.0",
       "variant_id": "6950",
       "variant_name": "Tecno Pova 6 Pro (Meteorite Grey, 256 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Tecno-pova-6-pro-5g-meteorite-grey-256gb-12gb-ram-Front-Back-View_WwwWcu8.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3799,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "934407750759",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_PQl84Jr.png",
       "title": "Samsung Galaxy S24 Plus 5G",
       "HSN": "85171300",
       "description": "Take a look at the Samsung Galaxy S24+ smartphone, a remarkable combination of amazing technology and advanced sophistication. Discover the beauty of picture editing with AI power. You can now easily edit your images to make sure each one is flawless. These cameras will make sure you leave with a picture that is pixel-perfect, whether you're zooming in, snapping a particularly lovely selfie, or capturing wide-angle photos. An impressive pixel powerhouse that promises no letdown. At all. Take high-resolution pictures that will surely survive the test of time for many years to come.",
       "mrp": 109999,
       "price": 109999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Samsung-galaxy-s24-plus-5g-cobalt-violet-12gb-512gb-Front-Back-View.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "samsung-galaxy-s24-plus-5g",
       "lastedit_date": "2024-04-18T13:42:16.539346",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 185,
       "sub_sub_category": null,
       "brand_name": 220,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "109999.0",
       "variant_id": "6937",
       "variant_name": "SAMSUNG Galaxy S24 Plus 5G (Onyx Black, 256 GB) (12 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-s24-plus-5g-onyx-black-512gb-12gb-ram-Front-Back-View_fqoRcxE.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3798,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "5221657154289",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_JU3i5cC.png",
       "title": "Samsung Galaxy S24 Ultra 5G",
       "HSN": "85171300",
       "description": "Behold the Samsung Galaxy S24 Ultra smartphone, an exceptional amalgamation of incredible technology and superior sophistication. Whether you're typing up a storm or jotting something down, Note Assist makes a long story short. New AI-powered editing options let you get the photo you want, like relocating objects and intelligently filling in the space they left behind. With a durable shield of titanium built right into the frame and better scratch resistance with Corning Gorilla Armor, your IP68 water and dust-resistant Galaxy S24 Ultra is ready for adventure. Write, tap, and navigate with the precision your fingers wish they had on the new, flat display.",
       "mrp": 164999,
       "price": 159999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Samsung-galaxy-s24-ultra-5g-titanium-violet-12gb-512gb-Front-Back-View_wmxlZuH.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "samsung-galaxy-s24-ultra-5g",
       "lastedit_date": "2024-04-18T12:55:14.028022",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 185,
       "sub_sub_category": null,
       "brand_name": 220,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "159999.0",
       "variant_id": "6929",
       "variant_name": "SAMSUNG Galaxy S24 Ultra 5G (Titanium Gray, 256 GB) (12 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-s24-ultra-5g-titanium-gray-512gb-12gb-ram-Front-Back-View_Wdipu1.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3797,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "5389216607821",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_rAh2saP.png",
       "title": "Samsung Galaxy S24 5G",
       "HSN": "85171300",
       "description": "Behold the Samsung Galaxy S24 smartphone, an exceptional amalgamation of incredible technology and superior sophistication. Unlock the magic of AI-powered photo editing. Now you can effortlessly perfect your photos, ensuring every image shines. Whether you're taking a super sweet selfie, shooting wide-angle pics, or zooming in, these cameras will help ensure you leave with a pixel-perfect shot. A true pixel powerhouse that will not disappoint. Ever. Snap high-res pics for that will no doubt withstand the test of time for years to come.",
       "mrp": 79999,
       "price": 79999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Samsung-galaxy-s24-5g-amber-yellow-512gb-8gb-ram-Front-Back-View_uUeKuEN.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "samsung-galaxy-s24-5g",
       "lastedit_date": "2024-04-17T18:57:35.779104",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 185,
       "sub_sub_category": null,
       "brand_name": 220,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "79999.0",
       "variant_id": "6924",
       "variant_name": "SAMSUNG Galaxy S24 5G (Cobalt Violet, 256 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-s24-5g-cobalt-violet-512gb-8gb-ram-Front-Back-View_AmWkL2H.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3796,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "2254785907374",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_QGX7cMK.png",
       "title": "OnePlus 12R 5G",
       "HSN": "85171300",
       "description": "About this item Fast & Smooth for years: Snapdragon 8 Gen 2 Mobile Platform, Up to 16GB of LPDDR5X RAM with RAM-Vita - Dual Cryo-velocity VC Cooling System, TÜV SÜD 48-Month Fluency Rating A Pristine Display with Aqua Touch: Super-Bright 1.5K LTPO ProXDR Display with Dolby Vision, and a DisplayMate A+ rating, Intellignent Eye Care certified by TÜV Rheinland, 4500 nits Peak Brightness, Aqua Touch helps you stay swiping, even with wet hands Computational Photography That's Incomparable: RAW HDR Algorithm, 50MP Sony IMX890 Camera and Ultra-wide Camera 112° FoV Sony IMX355, Ultra-Clear Image Quality Our Longest-Lasting Battery Ever: 5500 mAh Battery with 100W SUPERVOOC, Paired with our advanced Battery Health Engine for longevity Smoother and more stable connectivity: WiFi 7 Ready, Enhanced Wi-Fi, Lower gaming latency, Reduced network recovery time.",
       "mrp": 39999,
       "price": 37780,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Oneplus-12r-5g-cool-blue-256gb-16gb-ram-front-Back-View_nn1AmmG.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "oneplus-12r-5g",
       "lastedit_date": "2024-04-17T17:27:03.898480",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 188,
       "sub_sub_category": null,
       "brand_name": 226,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "37780.0",
       "variant_id": "6919",
       "variant_name": "OnePlus 12R (Iron Gray, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Oneplus-12r-5g-iron-gray-256gb-16gb-ram-Front-Back-View_R1q82Eg.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3795,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "5119882436672",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_NyuEpf8.png",
       "title": "Redmi A3",
       "HSN": "85171300",
       "description": "",
       "mrp": 9999,
       "price": 6999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/redmi-a3-midnight-black-128gb-6gb-ram-front-back-view_G9XIdXi.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "redmi-a3",
       "lastedit_date": "2024-04-17T17:05:12.701753",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 179,
       "sub_sub_category": null,
       "brand_name": 224,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "6999.0",
       "variant_id": "6911",
       "variant_name": "REDMI A3 (Midnight Black, 64 GB) (3 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/redmi-a3-midnight-black-128gb-6gb-ram-front-back-view_G9XIdXi.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3794,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "450913488138",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_Y2K3FWh.png",
       "title": "Tecno Spark GO 2024",
       "HSN": "85171300",
       "description": "Looks for Function with Style: Segment first 6.56-inch Dot-in Display and Dynamic Port, the 90Hz refresh rate ensures a smooth scrolling experience. \"Bounce on Dual Stereo Speaker: Segment-first Dual Stereo Speakers equipped with DTS technology provide a fully immersive listening experience of up to 400%* volume than a single speaker. (*Basis internal test data under standard condition)\" Deserves a Best in Class Security: This device with Anti-oil Side Fingerprint Unlocking is built for comfort and efficiency, allowing you to easily unlock it, with a touch of your fingertip. \"Powered by Massive Storage: Capable of managing multiple applications and tasks simultaneously, with up to 6GB* of RAM & 64GB of ROM, It includes a dedicated SD card slot for up to 1TB expansion. (*With Memory Fusion)\" Thrive on Unbeatable Performance: Our Octa-Core T606 processor delivers lightning-fast performance, stepping in at an astonishing peak frequency, leaving no room for hanging or lagging complaints. Captured in Magical Frames: 13MP dual camera with wide aperture and HDR for sharpness. 8MP selfie camera with beauty enhancements and dual flash for ideal lighting. Fueled by Uninterrupted Power: Experience an endless realm of films and music with this massive 5000mAh battery. Boost your experience by using a versatile Type-C charger with 10W. Beautifully crafted design: 8.55mm slim and bold flat design. Keep up with the latest industry trends. Its straight lines and rounded corners give it a tough and trendy look",
       "mrp": 7499,
       "price": 6899,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Tecno-spark-go-2024-mystery-white-3gb-64gb-ram-Front-Back-View_Nz0LoW2.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "tecno-spark-go-2024",
       "lastedit_date": "2024-04-23T12:07:02.389319",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 179,
       "sub_sub_category": null,
       "brand_name": 224,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "6899.0",
       "variant_id": "6903",
       "variant_name": "Tecno Spark Go 2024 (Magic Skin Green, 64 GB) (3 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Tecno-spark-go-2024-magic-skin-green-64gb-3gb-ram-Front-Back-View_yeCz4sf.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3793,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "9459059536370",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_KHJkOqc.png",
       "title": "Tecno Pova 5 Pro 5G",
       "HSN": "85171300",
       "description": "With its 68 W Ultra Fast Charging capability, the Tecno POVA 5 Pro 5G redefines perfection in smartphone technology. It can charge from 0% to 50% in just 15 minutes, allowing for continuous use. Your style is enhanced by its unique backlit design and customisable lighting effects. With VC liquid cooling technology, you can keep cool and experience unparalleled performance thanks to the MediaTek Dimensity 6080 5G CPU. Enjoy entertainment to the fullest on the bright 17.22 cm (6.678) FHD+ display with a refresh rate of 120 Hz. With the 16 MP front-facing camera and the 50 MP dual back camera, you can capture every moment. Take advantage of expandable storage of up to 1 TB, up to 16 GB of RAM, and dual 5G capability.",
       "mrp": 15990,
       "price": 14999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Tecno-pova-5-pro-5g-dark-illusion-256gb-8gb-ram-Front-and-Back-View_wpcMQdf.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "tecno-pova-5-pro-5g",
       "lastedit_date": "2024-04-17T14:33:20.569389",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 179,
       "sub_sub_category": null,
       "brand_name": 224,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "14999.0",
       "variant_id": "6900",
       "variant_name": "Tecno Pova 5 Pro 5G (Silver Fantasy, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Tecno-pova-5-pro-5g-silver-fantasy-256gb-8gb-ram-Front-and-Back-View-min.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3792,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "3323133318359",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_r1IKWdS.png",
       "title": "Samsung Galaxy S22 5G",
       "HSN": "85171300",
       "description": "Explore a new range of night photography features on this Samsung Galaxy S22 5G smartphone. You can click stunning images even in low light with the Nightography mode. It is designed with a pro-grade camera which comprises a big pixel sensor that welcomes more light for mind-blowing photography. Built with impressive software and hardware, this phone is a game-changer. With a 120 Hz refresh rate and dynamic AMOLED 2x display, you are going to experience immersive screen time. This phone operates on a Snapdragon 8 Gen 1 processor that delivers quick and hassle- free navigation. This device is protected by Corning Gorilla Glass Victus and has an IP68 waterproof rating.",
       "mrp": 85999,
       "price": 36999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Samsung-Galaxy-S22-5G-Bora-Purple-99_v6l4bAg.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "samsung-galaxy-s22-5g",
       "lastedit_date": "2024-04-23T12:02:59.861377",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 185,
       "sub_sub_category": null,
       "brand_name": 220,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "36999.0",
       "variant_id": "6895",
       "variant_name": "SAMSUNG Galaxy S22 5G (Phantom Black, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-galaxy-s22-5g-phantom-black-256gb-8gb-ram-Front-Back-View_uPbNOLa.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3791,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "5139156986290",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_w6D7s8e.png",
       "title": "Xiaomi 14 5G",
       "HSN": "85171300",
       "description": "Experience the pinnacle of photography with the Xiaomi 14, the product of the innovative partnership between Xiaomi and Leica. With three 50 MP Leica cameras, you can unleash your imagination and capture the subtleties of life with unmatched clarity. With its wide aperture, the primary 50 MP Summilux camera steals the show and produces amazing pictures across a range of lighting settings. Leica Cinematography has remarkable cinematic qualities, providing GoPro and Dolby Vision video recording. The phone's design guarantees an immersive viewing experience with its ultra-comfortable grip and state-of-the-art display technology. The Snapdragon 8 Gen 3-powered Xiaomi 14 skillfully strikes a mix between economy and performance. With the 90 W HyperCharge, charging is simplified. Its IP68 certification ensures durability, and its CCG technology provides maximum performance when charging.",
       "mrp": 79999,
       "price": 69999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/xiaomi-14-5g-white-512gb-12gb-ram-front-back-view.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "xiaomi-14-5g",
       "lastedit_date": "2024-04-11T17:22:02.762905",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 205,
       "sub_sub_category": null,
       "brand_name": 219,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "69999.0",
       "variant_id": "6881",
       "variant_name": "Xiaomi 14 5G (Jade Green, 512 GB) (12 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/xiaomi-14-5g-jade-green-512gb-12gb-ramfront-back-view.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3790,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "8274100695923",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_aPMcyhL.png",
       "title": "Redmi Note 13 Pro Plus 5G",
       "HSN": "85171300",
       "description": "\r\nThe Redmi Note 13 Pro+ 5G is a symphony of innovation, luxury, and power. With Fusion Design, a 3D Curved AMOLED Display, In-Display Fingerprint Sensor, Sharp 1.5K Resolution, Flagship IP68 Protection, Elegance Meets Endurance, True 200 MP With OIS, 120 W HyperCharge, and the Global Debut of the MediaTek Dimensity 7200 Ultra-5G, this SuperNote transcends the realm of smartphones. It's a masterpiece that blends art and technology seamlessly, offering an unparalleled experience that goes beyond expectations. Elevate your mobile journey with the Redmi Note 13 Pro+ 5G – where innovation meets perfection.",
       "mrp": 37999,
       "price": 35999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/redmi-note-13-pro-plus-5g-fusion-white-12gb-512gb-ram-front-back-view.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "redmi-note-13-pro-plus-5g",
       "lastedit_date": "2024-04-11T16:30:03.369925",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 193,
       "sub_sub_category": null,
       "brand_name": 222,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "35999.0",
       "variant_id": "6873",
       "variant_name": "REDMI Note 13 Pro Plus 5G (Fusion Purple, 256 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/redmi-note-13-pro-plus-5g-fusion-purple-256gb-8gb-ram-front-back-view_W6hKPUe.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3789,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "1470675293872",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_EDjzGN9.png",
       "title": "Redmi Note 13 PRO 5G",
       "HSN": "85171300",
       "description": "The Redmi Note 13 Pro 5G is not just a smartphone; it's a testament to Xiaomi's commitment to innovation and user satisfaction. With its Pro design, pro camera setup, powerful processor, visual spectacle display, enduring elegance, seamless unlocking, rapid charging, and fan-favourite features, the Redmi Note 13 Pro 5G is the epitome of a next-gen smartphone. Elevate your mobile experience and make a statement with the Redmi Note 13 Pro 5G – where perfection meets Pro.",
       "mrp": 32999,
       "price": 29999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/redmi-note-13-pro-5g-midnight-black-256gb-12gb-ram-front-back-view.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "redmi-note-13-pro-5g",
       "lastedit_date": "2024-04-11T14:36:05.382847",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 193,
       "sub_sub_category": null,
       "brand_name": 222,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "29999.0",
       "variant_id": "6865",
       "variant_name": "REDMI Note 13 Pro 5G (Coral Purple, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/redmi-note-13-pro-5g-coral-purple-128gb-6gb-ram-front-back-view_2sYXJSY.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3788,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "4087657783352",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_yoGWd6N.png",
       "title": "Redmi Note 13 5G",
       "HSN": "85171300",
       "description": "NA",
       "mrp": 24999,
       "price": 20875,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/redmi-note-13-5g-stealth-black-256gb-8gb-ram-front-back-view.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "redmi-note-13-5g",
       "lastedit_date": "2024-04-11T12:50:40.785178",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 193,
       "sub_sub_category": null,
       "brand_name": 222,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "20875.0",
       "variant_id": "6857",
       "variant_name": "REDMI Note 13 5G (Arctic White, 128 GB) (6 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/redmi-note-13-5g-arctic-white-256gb-8gb-ram-front-back-view_CWBCeSM.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3787,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "2811083730216",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_OIAoKm9.png",
       "title": "Realme 12x 5G",
       "HSN": "85171300",
       "description": "The Realme 12x 5G is a sleek powerhouse redefining mobile technology. Swift charging meets endurance with 45 W SUPERVOOC Charge and a 5000 mAh battery, ensuring you're always connected. The Dimensity 6100+ 6nm chipset delivers lightning-fast 5G speeds for seamless connectivity wherever you are. Immerse yourself in the 12.07 cm (6.72) 120 Hz FHD+ Display, offering crystal-clear visuals with its ultra-smooth refresh rate. Style meets substance with its ultra-slim 7.69 mm profile and lightweight 188g body. Capture life's moments in stunning detail with the 50 MP AI camera, while the vapour chamber cooling system keeps performance optimal. Elevate your audio experience with dual stereo speakers, delivering Hi-Res Audio certification for immersive sound. The Realme 12x 5G: where innovation meets elegance in the palm of your hand.",
       "mrp": 18999,
       "price": 14999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Realme-12x-5g-twilight-purple-128gb-8gb-ram-Front-Back-View.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "realme-12x-5g",
       "lastedit_date": "2024-04-11T11:40:18.022136",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 182,
       "sub_sub_category": null,
       "brand_name": 221,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "14999.0",
       "variant_id": "6852",
       "variant_name": "realme 12x 5G (Twilight Purple, 128 GB) (4 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Realme-12x-5g-twilight-purple-128gb-8gb-ram-Front-Back-View_iKxvbjZ.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3786,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "1671823859445",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_CE1TVkl.png",
       "title": "Realme 12 Pro Plus 5G",
       "HSN": "85171300",
       "description": "In a world where innovation reigns supreme, the realme 12 Pro+ 5G stands tall as a beacon of superior technology and design. Elevate your mobile experience, capture moments with unprecedented clarity, and stay connected with seamless performance. Behold this realme smartphone – where every feature is a testament to a commitment to pushing the boundaries of what's possible in a smartphone.",
       "mrp": 37999,
       "price": 33999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/Realme-12-pro-plus-5g-navigator-beige-8gb-128gb-ram-Front-Back-View.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "realme-12-pro-plus-5g",
       "lastedit_date": "2024-04-10T19:04:42.638138",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 182,
       "sub_sub_category": null,
       "brand_name": 221,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "33999.0",
       "variant_id": "6844",
       "variant_name": "realme 12 Pro Plus 5G (Explorer Red, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/realme-12-pro-plus-5g-explorer-red-128gb-8gb-ram-front-back-view_3CmFQy2.webp",
       "stock_sataus": "In-stock"
   },
   {
       "id": 3785,
       "Meta_Title": "",
       "Meta_Description": "",
       "Meta_Keyword": "",
       "bar_code": "1770196714535",
       "bar_code_image": "https://crazzyhub.s3.amazonaws.com/media/barcode_images/barcode_unique_no_90bf5Oc.png",
       "title": "Realme 12 Pro 5G",
       "HSN": "85171300",
       "description": "\r\nIn a world dominated by innovation, the realme 12 Pro 5G stands out as a beacon of excellence. It's not just a smartphone; it's a testament to realme's dedication to pushing the boundaries of what's possible. Elevate your mobile experience, capture moments with unprecedented clarity, and indulge in a device that seamlessly blends performance, design, and cutting-edge technology. Choose realme – where every feature is a step toward a future of limitless possibilities.",
       "mrp": 29999,
       "price": 24999,
       "discount_percent": 0,
       "quantity": 10,
       "image": "https://crazzyhub.s3.amazonaws.com/media/store_prod/realme-12-pro-5g-Navigator-beige-256gb-8gb-ram-front-back-view_XLLktVW.webp",
       "arriving_soon": false,
       "show_for_user": true,
       "is_wallet": false,
       "is_bestseller": false,
       "admin_permission": "Approved",
       "slug": "realme-12-pro-5g",
       "lastedit_date": "2024-04-10T18:02:10.279464",
       "overview": "",
       "videos": "",
       "sgst": 0,
       "cgst": 0,
       "igst": 0,
       "is_active_for_user": true,
       "is_active_return": false,
       "is_active_replacement": false,
       "store_id": 1,
       "main_category": 28,
       "sub_category": 182,
       "sub_sub_category": null,
       "brand_name": 221,
       "permission": 1,
       "frequently_bought_together": [],
       "whishlist_status": "login_required",
       "add_to_cart_status": "login_required",
       "actual_price": "24999.0",
       "variant_id": "6839",
       "variant_name": "realme 12 Pro 5G (Submarine Blue, 128 GB) (8 GB RAM)",
       "variant_image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/realme-12-pro-5g-submarine-blue-256gb-8gb-ram-front-back-view_fqM3tIg.webp",
       "stock_sataus": "In-stock"
   }
 ];
 
//  const Applayout = () => {
//    return (
//      <>
//        <Mobile />
//        <div className="RestCard">
//          <RestrauntCard  mob_data={mob_data[0]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[1]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[2]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[3]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[4]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[5]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[6]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[7]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[8]}></RestrauntCard>
//          <RestrauntCard  mob_data={mob_data[9]}></RestrauntCard>
//        </div>
//      </>
//    );
//  };
// export default Applayout;
const Applayout = () => {
    return (
      <>
        <Mobile />
        <div className="RestCard">
          {mob_data.map((data, index) => (
            <RestrauntCard key={index} mob_data={data}></RestrauntCard>
          ))}
        </div>
      </>
    );
  };
  
  export default Applayout;
  